name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install package and dependencies
        run: |
          python3 -m pip install .[test]
      - name: Run all tests
        run: |
          python -m pytest -sv ./tests/*
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
      - name: Build and push the container image
        run: |
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && IMAGE_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//') || IMAGE_VERSION="latest"
          docker buildx build . --push --file ./Dockerfile --tag ${{ env.REGISTRY }}/ai4work-project/logistics-scheduler-kafka:$IMAGE_VERSION
